from block import Block
import random

class Blocks(Block):
    def __init__(self):
        super().__init__()
        self.hideturtle()
        self.stamp_id_list = []
        self.stamp_pos_id_list = []
        self.yellow_blocks = []
        self.orange_blocks = []
        self.blue_blocks = []
        self.light_blue_blocks = []
        self.green_blocks = []
        self.red_blocks = []
        self.purple_blocks = []

    def o_block(self):
        self.color("yellow")
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.yellow_blocks.append(self.pos())
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.yellow_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.yellow_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.yellow_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        self.rt(90)

    def l_block(self):
        self.color("orange")
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.orange_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.orange_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.orange_blocks.append(self.pos())
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.orange_blocks.append(self.pos())
        self.rt(180)
        self.forward(30)

    def j_block(self):
        self.color("blue")
        self.back(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.blue_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.blue_blocks.append(self.pos())
        self.lt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.blue_blocks.append(self.pos())
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.blue_blocks.append(self.pos())
        self.back(30)

    def i_block(self):
        self.color("light blue")
        self.back(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.light_blue_blocks.append(self.pos())
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.light_blue_blocks.append(self.pos())
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.light_blue_blocks.append(self.pos())
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.light_blue_blocks.append(self.pos())
        self.back(60)

    def s_block(self):
        self.color("green")
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.green_blocks.append(self.pos())
        self.back(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.green_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.green_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.green_blocks.append(self.pos())
        self.back(30)
        self.rt(180)

    def z_block(self):
        self.color("red")
        self.back(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.red_blocks.append(self.pos())
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.red_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.red_blocks.append(self.pos())
        self.lt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.red_blocks.append(self.pos())
        self.back(30)

    def t_block(self):
        self.color("purple")
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.purple_blocks.append(self.pos())
        self.rt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.purple_blocks.append(self.pos())
        self.lt(90)
        self.forward(30)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.purple_blocks.append(self.pos())
        self.back(60)
        stamp = self.stamp()
        self.stamp_id_list.append(stamp)
        self.stamp_pos_id_list.append(self.pos())
        self.purple_blocks.append(self.pos())
        self.forward(30)

    block_methods = {
        "i": i_block, 
        "t": t_block, 
        "s": s_block,
        "z": z_block,
        "j": j_block,
        "l": l_block,
        "o": o_block
    }